export const routePaths = {
  home: '/',
  sports: '/sports',
  venues: '/venues',
  courts: '/courts',
  courtDetail: '/courts/:courtId',
  login: '/login',
  register: '/register',
  profile: '/profile',
  bookingHistory: '/bookings',
  vendorDashboard: '/vendor',
  vendorVenues: '/vendor/venues',
  vendorCourts: '/vendor/courts',
  vendorBookings: '/vendor/bookings',
  adminDashboard: '/admin',
  adminSports: '/admin/sports',
  adminUsers: '/admin/users',
  adminVenues: '/admin/venues',
  adminCourts: '/admin/courts',
  adminBookings: '/admin/bookings',
} as const;
