CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT uk_roles_name UNIQUE (name),
    CONSTRAINT chk_roles_name CHECK (name IN ('USER', 'VENDOR', 'ADMIN'))
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    avatar_url VARCHAR(500),
    password VARCHAR(255),
    role_id BIGINT NOT NULL,
    provider VARCHAR(30) NOT NULL DEFAULT 'LOCAL',
    provider_id VARCHAR(255),
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING_VERIFICATION',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles (id),
    CONSTRAINT chk_users_provider CHECK (provider IN ('LOCAL', 'GOOGLE')),
    CONSTRAINT chk_users_status CHECK (status IN ('PENDING_VERIFICATION', 'ACTIVE', 'INACTIVE'))
);

CREATE TABLE email_verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_email_verification_tokens_token UNIQUE (token),
    CONSTRAINT fk_email_verification_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE sports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sports_name UNIQUE (name),
    CONSTRAINT chk_sports_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE venues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    address VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    phone VARCHAR(20) NOT NULL,
    opening_time TIME NOT NULL,
    closing_time TIME NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_venues_vendor FOREIGN KEY (vendor_id) REFERENCES users (id),
    CONSTRAINT chk_venues_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT chk_venues_business_hours CHECK (opening_time < closing_time)
);

CREATE TABLE courts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    sport_id BIGINT NOT NULL,
    venue_id BIGINT NOT NULL,
    price_per_hour NUMERIC(12, 2) NOT NULL,
    description VARCHAR(1000),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_courts_sport FOREIGN KEY (sport_id) REFERENCES sports (id),
    CONSTRAINT fk_courts_venue FOREIGN KEY (venue_id) REFERENCES venues (id),
    CONSTRAINT chk_courts_price_per_hour CHECK (price_per_hour >= 0),
    CONSTRAINT chk_courts_status CHECK (status IN ('ACTIVE', 'MAINTENANCE', 'INACTIVE'))
);

CREATE TABLE venue_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id BIGINT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    public_id VARCHAR(255),
    sort_order INTEGER NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_venue_images_venue FOREIGN KEY (venue_id) REFERENCES venues (id),
    CONSTRAINT uk_venue_images_sort_order UNIQUE (venue_id, sort_order),
    CONSTRAINT chk_venue_images_sort_order CHECK (sort_order >= 0)
);

CREATE TABLE court_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    court_id BIGINT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    public_id VARCHAR(255),
    sort_order INTEGER NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_court_images_court FOREIGN KEY (court_id) REFERENCES courts (id),
    CONSTRAINT uk_court_images_sort_order UNIQUE (court_id, sort_order),
    CONSTRAINT chk_court_images_sort_order CHECK (sort_order >= 0)
);

CREATE TABLE time_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT uk_time_slots_time_range UNIQUE (start_time, end_time),
    CONSTRAINT chk_time_slots_time_range CHECK (start_time < end_time),
    CONSTRAINT chk_time_slots_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE court_time_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    court_id BIGINT NOT NULL,
    time_slot_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_court_time_slots_court FOREIGN KEY (court_id) REFERENCES courts (id),
    CONSTRAINT fk_court_time_slots_time_slot FOREIGN KEY (time_slot_id) REFERENCES time_slots (id),
    CONSTRAINT uk_court_time_slots_court_time_slot UNIQUE (court_id, time_slot_id),
    CONSTRAINT chk_court_time_slots_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    court_id BIGINT NOT NULL,
    time_slot_id BIGINT NOT NULL,
    booking_date DATE NOT NULL,
    total_price NUMERIC(12, 2) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    note VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bookings_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_bookings_court FOREIGN KEY (court_id) REFERENCES courts (id),
    CONSTRAINT fk_bookings_time_slot FOREIGN KEY (time_slot_id) REFERENCES time_slots (id),
    CONSTRAINT fk_bookings_court_time_slot FOREIGN KEY (court_id, time_slot_id) REFERENCES court_time_slots (court_id, time_slot_id),
    CONSTRAINT chk_bookings_total_price CHECK (total_price >= 0),
    CONSTRAINT chk_bookings_status CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELLED', 'COMPLETED'))
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    method VARCHAR(30) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'UNPAID',
    provider_transaction_id VARCHAR(255),
    paid_at TIMESTAMP,
    refund_amount NUMERIC(12, 2),
    refund_reason VARCHAR(500),
    refunded_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payments_booking FOREIGN KEY (booking_id) REFERENCES bookings (id),
    CONSTRAINT uk_payments_booking UNIQUE (booking_id),
    CONSTRAINT chk_payments_method CHECK (method IN ('VNPAY', 'CASH_AT_COURT')),
    CONSTRAINT chk_payments_status CHECK (status IN ('UNPAID', 'PENDING', 'PAID', 'FAILED', 'REFUND_PENDING', 'REFUNDED', 'REFUND_FAILED')),
    CONSTRAINT chk_payments_amount CHECK (amount >= 0),
    CONSTRAINT chk_payments_refund_amount CHECK (refund_amount IS NULL OR refund_amount >= 0)
);

CREATE INDEX idx_users_role_id ON users (role_id);
CREATE INDEX idx_email_verification_tokens_user_id ON email_verification_tokens (user_id);
CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);
CREATE INDEX idx_venues_vendor_id ON venues (vendor_id);
CREATE INDEX idx_courts_sport_id ON courts (sport_id);
CREATE INDEX idx_courts_venue_id ON courts (venue_id);
CREATE INDEX idx_venue_images_venue_id ON venue_images (venue_id);
CREATE INDEX idx_court_images_court_id ON court_images (court_id);
CREATE INDEX idx_court_time_slots_court_id ON court_time_slots (court_id);
CREATE INDEX idx_court_time_slots_time_slot_id ON court_time_slots (time_slot_id);
CREATE INDEX idx_bookings_user_id ON bookings (user_id);
CREATE INDEX idx_bookings_court_id ON bookings (court_id);
CREATE INDEX idx_bookings_time_slot_id ON bookings (time_slot_id);
CREATE INDEX idx_bookings_booking_date ON bookings (booking_date);
CREATE INDEX idx_payments_status ON payments (status);
