DROP INDEX IF EXISTS uk_bookings_active_slot;

CREATE TABLE booking_time_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    court_id BIGINT NOT NULL,
    booking_date DATE NOT NULL,
    time_slot_id BIGINT NOT NULL,
    slot_price NUMERIC(12, 2) NOT NULL,
    active_slot_key VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_booking_time_slots_booking FOREIGN KEY (booking_id) REFERENCES bookings (id),
    CONSTRAINT fk_booking_time_slots_court FOREIGN KEY (court_id) REFERENCES courts (id),
    CONSTRAINT fk_booking_time_slots_time_slot FOREIGN KEY (time_slot_id) REFERENCES time_slots (id),
    CONSTRAINT fk_booking_time_slots_court_slot FOREIGN KEY (court_id, time_slot_id)
        REFERENCES court_time_slots (court_id, time_slot_id),
    CONSTRAINT uk_booking_time_slots_booking_slot UNIQUE (booking_id, time_slot_id),
    CONSTRAINT chk_booking_time_slots_price CHECK (slot_price >= 0)
);

INSERT INTO booking_time_slots (
    booking_id,
    court_id,
    booking_date,
    time_slot_id,
    slot_price,
    active_slot_key
)
SELECT
    id,
    court_id,
    booking_date,
    time_slot_id,
    total_price,
    CASE
        WHEN status IN ('PENDING', 'CONFIRMED')
            THEN CONCAT(court_id, ':', booking_date, ':', time_slot_id)
        ELSE NULL
    END
FROM bookings;

ALTER TABLE bookings DROP CONSTRAINT IF EXISTS fk_bookings_court_time_slot;
ALTER TABLE bookings DROP CONSTRAINT IF EXISTS fk_bookings_time_slot;
DROP INDEX IF EXISTS idx_bookings_time_slot_id;
ALTER TABLE bookings DROP COLUMN time_slot_id;

CREATE INDEX idx_booking_time_slots_booking_id
    ON booking_time_slots (booking_id);

CREATE INDEX idx_booking_time_slots_court_date
    ON booking_time_slots (court_id, booking_date);
